root: ./book

structure:
	readme: README.md
	summary: SUMMARY.md

redirects:
	help/contact: contact.md
	make/contact: /contact.md
	you/contact: ./contact.md
	better/contact: ./book/contact.md
	butter/contact: ../contact.md
	ron/contact: ./README.md